# ADITIM Monitor Configuration

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/aditim-monitor.log"

monitoring:
  collection_interval: 60  # seconds
  max_workers: 10

database:
  host: "localhost"
  port: 5432
  database: "aditim_monitor"
  username: "monitor_user"
  password: "monitor_pass"

collectors:
  - name: "http_check"
    type: "HttpCollector"
    config:
      targets:
        - url: "https://example.com"
          timeout: 30
        - url: "https://api.example.com/health"
          timeout: 10
          
  - name: "system_metrics"
    type: "SystemCollector"
    config:
      metrics:
        - "cpu_usage"
        - "memory_usage"
        - "disk_usage"

alerting:
  rules:
    - name: "High CPU Usage"
      metric_name: "cpu_usage"
      condition: "> 90"
      duration: 300
      severity: "warning"
      
    - name: "Service Down"
      metric_name: "http_check_status"
      condition: "== 0"
      duration: 60
      severity: "critical"
